# AI 代码审核配置文件
# 请根据实际情况修改以下配置

# Moonshot/Kimi API 配置
moonshot_api_key: your-api-key-here
moonshot_api_base: https://api.moonshot.cn/v1

# Azure DevOps Wiki 配置
wiki_url_base: https://dev.azure.com/your-org/your-project/_apis/wiki/wikis/your-wiki.wiki/pages
wiki_pat: your-pat-token-here

# 代码审核配置
pr_only: true  # 是否只审核 PR/commit 变更代码
standards: ai_code_review/standards/python_standards.txt  # 代码标准文件路径

# 支持的代码文件类型
code_types:
  - '.py'
  - '.js'
  - '.ts'
  - '.jsx'
  - '.tsx'
  - '.java'
  - '.go'
  - '.cpp'
  - '.vue'
  - '.html'
  - '.css' 